sudo: required
language: generic
services:
  - docker


before_install:
  - docker build -t victorrosario/DockerReact -f Dockerfile.dev .

script:
  - docker run -e CI=true victorrosario/DockerReact npm run test